### ISSUE TITLE
Comparison with RZCOBS

### ISSUE THREAD

**Issue by YandiBanyuKarimaWaly** [rokath/tcobs#26]
So I stumbled upon your repo when trying to find a good way to send [Capnproto encoded](https://capnproto.org/encoding.html) data from MCU. Initially I was going to use the provided [packing](https://capnproto.org/encoding.html#packing) and then frame it with reverse-cobs. But then I saw the [RZCOBS](https://github.com/Dirbaio/rzcobs) from the same repo owner. Anyway, I ended up using TCOBS since RZCOBS require additional processing of padded zero byte. However, on your roadmap I see that you are making comparison against the V1 of TCOBS, so you may also want to make comparison against RZCOBS too.

**Comment by rokath** [comment]
Good idea, but duplicate. Hopefully I will find time for this one day. Anyway, feel free to do it yourself and share the results.
