### ISSUE TITLE
Add reference test data for TCOBS compression benchmarking 

### ISSUE THREAD

**Issue by gresolio** [rokath/TCOBS#3]
TCOBS looks interesting. I would like to compare it against plain COBS, and other compression algorithms.
Can you please add some reference test data? For example, just a text file, where each line contains bytes in hex:
```
01 00 00 00
FF FF FF FF
01 02 01 02 AA BB AA BB
...
```
Of course I can just use a random data set (and this can also be included later for comparison), but reference test data are preferred, for which TCOBS is being developed in the first place. Such reference examples should at least roughly reflect typical data patterns, the approximate min/max length of messages, and serve as initial benchmark data for anyone interested.

p.s. If text files are inconvenient, the data can be saved in any other format more suitable in your opinion.

**Comment by rokath** [comment]
Done: See [https://github.com/rokath/TCOBS/tree/master/pkg/tcobs/testdata](https://github.com/rokath/TCOBS/tree/master/pkg/tcobs/testdata).
